language: python
python:
  - 'pypy2.7'
  - 'pypy3.5'
  - '2.7'
  - '3.4'
  - '3.6'
  - 'nightly'
install:
  - pip install -r requirements.txt
  - pip install .
script:
  - coverage run --source=messagebird -m unittest discover -s tests/
  - coverage report --fail-under=80
  - pycodestyle --statistics --ignore=E121,E123,E126,E133,E226,E241,E242,E704,W503,W504,W505,E501 ./messagebird/
  - pycodestyle --statistics --ignore=E121,E123,E126,E133,E226,E241,E242,E704,W503,W504,W505,E501 ./tests/
matrix:
  allow_failures:
  - python: 'nightly'
  - python: 'pypy2.7'
  - python: 'pypy3.5'
