language: python
python:
  - 'pypy3.6'
  - 'pypy3.7'
  - '3.6'
  - '3.7'
  - '3.8'
  - '3.9'
  - 'nightly'
install:
  - pip install -e .[dev]
script:
  - coverage run --source=messagebird -m unittest discover -s tests/
  - coverage report --fail-under=80
  - pycodestyle --statistics --ignore=E121,E123,E126,E133,E226,E241,E242,E704,W503,W504,W505,E501 ./messagebird/
  - pycodestyle --statistics --ignore=E121,E123,E126,E133,E226,E241,E242,E704,W503,W504,W505,E501 ./tests/
matrix:
  allow_failures:
  - python: 'nightly'
